image: python:3.11

include: 
  - project: kernel-performance/perfqe-gitlab-ci-templates
    file: pypi/nexus.yml

  - project: kernel-performance/perfqe-gitlab-ci-templates
    file: llm/pr-agent.yml

stages:
  - test
  - style
  - review
  - publish

default:
  before_script:
    - pip install hatch

unittests:
  tags:
    - docker
  stage: test
  script: hatch run all:test
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: report*.xml


code-style:
  tags:
    - docker
  stage: style
  script: hatch run lint:style
    
