image: python:3.11

include: 
  - project: kernel-performance/perfqe-gitlab-ci-templates
    file: pypi/nexus.yml

stages:
  - test
  - style
  - publish

unittests:
  tags:
    - docker
  stage: test
  script: hatch run test

code-style:
  tags:
    - docker
  stage: style
  script: hatch run lint:style
    
