image: python:3.11

include: 
  - project: kernel-performance/perfqe-gitlab-ci-templates
    file: pypi/nexus.yml

stages:
  - test
  - publish

unittests:
  tags:
    - docker
  stage: test
  script: make test
