image: fedora

stages:
        - test

before_script:
        - dnf -y install python3 python3-pytest 

unittests:
        tags:
                - docker
        stage: test
        script: pytest-3


