image: python:3.6

stages:
        - test

unittests:
        tags:
                - docker
        stage: test
        script: 
          - pip install pipenv
          - pipenv install --dev
          - pipenv run pytest


