image: python:3.6

stages:
  - test
  - build

unittests:
  tags:
    - docker
  stage: test
  script:
    - pip install pipenv
    - pipenv install --dev
    - pipenv run pytest


build:
  tags:
    - docker
  stage: build
  needs:
    - unittests
  only:
    - /^v[0-9]*\.[0-9]*\.?[0-9]*$/
  except:
    - branches
  script:
    - pip install pulp-cli
    - python setup.py sdist

  artifacts:
    paths:
      - dist
    expire_in: 7 days